task/MA-7154: fix phoenix issues w/ version 4
mklein0/dbsurvey pull request #4
Opened 2020-10-23 21:21 UTC by deeTEEcee

Aside from extra small files that I'm working with locally, the main needs were:
* hbase config was missing from phoenix4 so i just copied the one in phoenix5 over. 
* to avoid confusion, i took out the symbolic link (`ln -s `) statement in the phoenix image.

2020-10-26 16:55 UTC, mklein0 requested changes

2020-10-26 16:55 UTC, mklein0 commented on phoenix4/orora-example-README.md
> +### Testing Orora Datavis ###
Proprietary.

2020-10-26 16:55 UTC, mklein0 commented on phoenix4/phoenix_test.py
> +    from ma.statengine.base import StatEngine
Proprietary

2020-11-18 20:45 UTC, deeTEEcee commented
Moved this over to a private repo.

2020-11-18 20:45 UTC, closed without merging